name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: bmhuyquoc104/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ 548b2e2d-4d40-4130-96a2-714e38146e6e }}
          GH_TOKEN: ${{ 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 }}
          SHOW_LANGUAGE:"true"


